#!/usr/bin/env bash


acti(){

		if [[ "$1" == "-a" || "$1" == "-activate" ]]; then

		source cli/activate

		source env/bin/activate

		echo "virtual environments activated..!!!"

		echo $FLASK_APP
		echo $FLASK_ENV

		fi
}


deactivate(){

		if [[ "$1" == "-d" || "$1" == "-deactivate" ]]; then

				source cli/deactivate

				#deactivate

				echo "deactivated...!!!"

				echo $FLASK_APP
				echo $FLASK_ENV

		fi
}



Help(){
printf "
Usage: initiate [options] ....

Options:

		To activate this script run  [source initiate -h]

		-h       -help         for help
		-d       -deactivate   to deactivate
		-a       -activate     to activate
"
}


case $1 in 

   -h|-H|-help|-Help|HELP)
		Help
		;;


   -d|-deactivate)
		deactivate $1
		;;


   -a|-activate)
		acti $1
		;;


   *)

printf "
helper: invalid option -- '$1'
  Use: initiate -h 
		"
		;;

esac
